sudo: false

language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

script:
  - php vendor/bin/phpunit

notifications:
  email: martin.aarhof@gmail.com
